[build]
  command = "yarn run build"
  functions = "functions"
  publish = "public"

[build.enviroment]
  NAME = "Build Aman"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[context.production.enviroment]
  NAME = "Aman Dhurwey"

[context.dev.environment]
  NAME = "Dev Aman"
