[build]
  command = "yarn run build"
  functions = "lambda"
  publish = "public"

[build.environment]
  NAME = "Build Aman"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[context.production.environment]
  NAME = "Aman Dhurwey"

[context.dev.environment]
  NAME = "Dev Aman"
