[build]
  command = "yarn run build"
  functions = "funtions"
  publish = "public"

[context.production.environment]
  NAME = "Production Aman"

[context.dev.environment]
  NAME = "Dev Aman"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
