[build]
  command = "yarn run build"
  functions = "build-funtions"
  publish = "public"

[build.environment]
  NAME = "Build Aman"
  
[context.production.environment]
  NAME = "Aman Dhurwey"

[context.dev.environment]
  NAME = "Dev Aman"
